shared:
  image: centos:centos7

jobs:
  job-1-1:
    steps:
      - echo: echo hoge
      
  job-1-4:
    requires:
      - sd@9297:job-1-3
    steps:
      - echo: echo hoge

  job-2-1:
    steps:
      - echo: echo hoge
  
  job-2-3:
    requires:
      - sd@9297:job-2-2
    steps:
      - echo: echo hoge
